export { authService } from "./auth.service";
export { archivesService } from "./archives.service";
export { usersService } from "./users.service";
export { rolesService } from "./roles.service";
export { logsService } from "./logs.service";
export { clientsService } from "./clients.service";
export { systemService } from "./system.service";
export { newsService } from "./news.service";
export { notaryService } from "./notary.service";
export { notificationsService } from "./notifications.service";
export { tasksService } from "./tasks.service";
export type { RoleItem } from "./roles.service";
export type { SystemConfig } from "./system.service";
export type { PaginatedNotifications } from "./notifications.service";
export type { PaginatedTasks } from "./tasks.service";
